name: ordermate
description: A new Flutter project.
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: ^3.1.2
  collection: any
  copy_with_extension: ^9.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.2
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^3.1.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  uuid: ^4.5.1
  intl: any
  permission_handler: ^12.0.1
  replay_bloc: ^0.3.0
  dart_mappable: ^4.6.0
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.0
  copy_with_extension_gen: ^9.1.0
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.9.3
  json_serializable: ^6.11.0
  dart_mappable_builder: ^4.6.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
